LibraryRental/Models/Author.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LibraryRental.Models
{
    public class Author
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        public string Name { get; set; }

        public virtual ICollection<Book> Books { get; set; }

        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    }
}

LibraryRental/Controllers/AuthorsController.cs
using LibraryRental.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using LibraryRental.ViewModel;

namespace LibraryRental.Controllers
{
    public class AuthorsController : Controller
    {
        private ApplicationDbContext _context;

        public AuthorsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Authors
        public ActionResult Index()
        {
            var authors = _context.Authors.ToList();
           
            return View(authors);
        }

        // GET: Authors/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult New()
        {
            var viewModel = new BookAuthorViewModel
            {
                Author = new Author(),
                Books = _context.Books.ToList()
            };

            return View("AuthorForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Author author)
        {
            if (!ModelState.IsValid)
            {
                return View("AuthorForm", author);
            }

            if (author.Id == 0)
            {
                _context.Authors.Add(author);
            } else
            {
                var authorInDb = _context.Authors.Single(a => a.Id == author.Id);
                authorInDb.Name = author.Name;
            }

            _context.SaveChanges();

            return View();
        }

        [HttpPut]
        // GET: Authors/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpDelete]
        // GET: Authors/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
    }
}

LibraryRental/Controllers/BooksController.cs
using LibraryRental.Models;
using LibraryRental.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryRental.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext _context;

        public BooksController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Books
        public ActionResult Index()
        {
            var books = _context.Books.ToList();
            return View(books);
        }

        // GET: Books/Details/5
        public ActionResult Details(int id)
        {
            var viewModel = new BookAuthorViewModel
            {
                Author = _context.Authors.Single(a => a.Id == id),
            };

            viewModel.Books = from book in viewModel.Author.Books
                              select book;

            return View(viewModel);
        }

        public ActionResult New()
        {
            var viewModel = new BookAuthorViewModel
            {
                Book = new Book
                {
                    Authors = new List<Author>(),
                },
                Authors = _context.Authors.ToList()
            };

            viewModel.SelectMultipleAuthors = new MultiSelectList(viewModel.Authors, "Id", "Name");

            return View("BookForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save()
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int id)
        {
            var book = _context.Books.SingleOrDefault(b => b.Id == id);

            if (book == null) return new HttpNotFoundResult();

            var viewModel = new BookAuthorViewModel
            {
                Book = book,
            };

            return View("BookForm", viewModel);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int id)
        {
            

            return View();
        }
    }
}

LibraryRental/Views/Authors/AuthorForm.cshtml
@model LibraryRental.ViewModel.BookAuthorViewModel

@{
    ViewBag.Title = "New";
}

<h2>Author Form</h2>

@using (Html.BeginForm("Save", "Authors"))  
{
    <div class="form-group">
        @Html.LabelFor(v => v.Author.Name)
        @Html.TextBoxFor(v => v.Author.Name, "", new { @class = "form-control" })
        @Html.ValidationMessageFor(v => v.Author.Name)
    </div>

    @Html.AntiForgeryToken()
    @Html.HiddenFor(a => a.Author.Id)
    <button type="submit" class="btn-primary">Submit</button>
}

LibraryRental/Views/Authors/Index.cshtml
@model IEnumerable<LibraryRental.Models.Author>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (!Model.Any())
{
    <text>No Customers yet</text>
}
else
{
    <table id="authors" class="table table-bordered table-responsive table-condensed table-hover table-condensed">
        <thead>
            <tr>
                <th>Author</th>
                <th>Books</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var author in Model)
            {
            <tr>
                <td>@Html.ActionLink(author.Name, "Edit", new { id = author.Id })</td>
                <td>@Html.ActionLink("Details", "Details", "Books", new { id = author.Id }, null)</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = author.Id })</td>
            </tr>
            }
        </tbody>
    </table>
}

@*@section scripts {
    <script>
        $(document).Ready(function () {
            var table = $("authors").DataTable({
                ajax: {
                    url: "/authors",
                    dataSrc = ""
                },

                columns: [
                    {
                        data: "name",
                        render: function (data, type, author) {
                            return "<a href='/authors/edit/" + author.id + "'>" + author.name + "</a>";
                        }
                    },
                    {
                        data: "books.title"
                    },
                    {
                        data: "id",
                    
                    }
                ]
            }) 
        })
    </script>
}*@